# Generated by Django 6.0 on 2025-12-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
